[package]
name = "rmqtt-cluster-raft"
version = "0.1.1"
authors = ["rmqtt <rmqttd@126.com>"]
edition = "2021"

[dependencies]
rmqtt = "0.2"
rmqtt-raft = "0.2.4"
serde = { version = "1.0", features = ["derive"] }
backoff = { version = "0.4", features = ["futures", "tokio"] }