[workspace]
members = [
    "rmqtt",
    "rmqtt-plugins/rmqtt-acl",
    "rmqtt-plugins/rmqtt-web-hook",
    "rmqtt-plugins/rmqtt-auth-http",
    "rmqtt-plugins/rmqtt-cluster-broadcast",
    "rmqtt-plugins/rmqtt-cluster-raft",
    "rmqtt-plugins/rmqtt-counter",
    "rmqtt-plugins/rmqtt-http-api",
    "rmqtt-bin",
    "rmqtt-macros"
]

[patch.crates-io]
rmqtt = { path = "rmqtt" }
rmqtt-macros = { path = "rmqtt-macros" }
rmqtt-acl = { path = "rmqtt-plugins/rmqtt-acl" }
rmqtt-web-hook = { path = "rmqtt-plugins/rmqtt-web-hook" }
rmqtt-auth-http = { path = "rmqtt-plugins/rmqtt-auth-http" }
rmqtt-cluster-broadcast = { path = "rmqtt-plugins/rmqtt-cluster-broadcast" }
rmqtt-cluster-raft = { path = "rmqtt-plugins/rmqtt-cluster-raft" }
rmqtt-counter = { path = "rmqtt-plugins/rmqtt-counter" }
rmqtt-http-api = { path = "rmqtt-plugins/rmqtt-http-api" }

[workspace.package]
version = "0.2.10"
edition = "2021"
authors = ["rmqtt <rmqttd@126.com>"]
description = "MQTT Server for v3.1, v3.1.1 and v5.0 protocols"
repository = "https://github.com/rmqtt/rmqtt.git"
license = "MIT license, Apache-2.0 License"
categories = ["network-programming"]
keywords = ["MQTT", "IoT", "messaging", "MQTT Server", "MQTT Broker"]
exclude = [".gitignore", ".cargo/config"]
rust-version = "1.64"