[workspace]
resolver = "2"
members = [
    "rmqtt",
    "rmqtt-plugins/rmqtt-plugin-template",
    "rmqtt-plugins/rmqtt-acl",
    "rmqtt-plugins/rmqtt-web-hook",
    "rmqtt-plugins/rmqtt-auth-http",
    "rmqtt-plugins/rmqtt-cluster-broadcast",
    "rmqtt-plugins/rmqtt-cluster-raft",
    "rmqtt-plugins/rmqtt-counter",
    "rmqtt-plugins/rmqtt-http-api",
    "rmqtt-plugins/rmqtt-retainer",
    "rmqtt-plugins/rmqtt-sys-topic",
    "rmqtt-plugins/rmqtt-session-storage",
    "rmqtt-plugins/rmqtt-message-storage",
    "rmqtt-bin",
    "rmqtt-macros"
]

[patch.crates-io]
rmqtt = { path = "rmqtt" }
rmqtt-macros = { path = "rmqtt-macros" }
rmqtt-plugin-template = { path = "rmqtt-plugins/rmqtt-plugin-template" }
rmqtt-acl = { path = "rmqtt-plugins/rmqtt-acl" }
rmqtt-web-hook = { path = "rmqtt-plugins/rmqtt-web-hook" }
rmqtt-auth-http = { path = "rmqtt-plugins/rmqtt-auth-http" }
rmqtt-cluster-broadcast = { path = "rmqtt-plugins/rmqtt-cluster-broadcast" }
rmqtt-cluster-raft = { path = "rmqtt-plugins/rmqtt-cluster-raft" }
rmqtt-counter = { path = "rmqtt-plugins/rmqtt-counter" }
rmqtt-http-api = { path = "rmqtt-plugins/rmqtt-http-api" }
rmqtt-retainer = { path = "rmqtt-plugins/rmqtt-retainer" }
rmqtt-sys-topic = { path = "rmqtt-plugins/rmqtt-sys-topic" }
rmqtt-session-storage = { path = "rmqtt-plugins/rmqtt-session-storage" }
rmqtt-message-storage = { path = "rmqtt-plugins/rmqtt-message-storage" }

[workspace.package]
version = "0.4.0"
edition = "2021"
authors = ["rmqtt <rmqttd@126.com>"]
description = "MQTT Server for v3.1, v3.1.1 and v5.0 protocols"
repository = "https://github.com/rmqtt/rmqtt.git"
license = "MIT license, Apache-2.0 License"
categories = ["network-programming"]
keywords = ["MQTT", "IoT", "messaging", "MQTT-Server", "MQTT-Broker"]
exclude = [".gitignore", ".cargo/config"]
rust-version = "1.71.1"


[workspace.dependencies]
rmqtt = "0.4"
rmqtt-macros = "0.1"
serde = "1.0"