[package]
name = "rmqtt-plugin-template"
version = "0.1.1"
authors = ["rmqtt <rmqttd@126.com>"]
edition = "2021"

[dependencies]
rmqtt = "0.3"
log = "0.4"
async-trait = "0.1.36"
tokio = "1.5"
bytestring = "1.0"