[package]
name = "rmqtt-plugin-template"
version = "0.1.1"
description = "RMQTT plugin template"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rmqtt.workspace = true
rmqtt-macros.workspace = true