##--------------------------------------------------------------------
## rmqtt-bridge-egress-pulsar
##--------------------------------------------------------------------

# See more keys and their definitions at https://github.com/rmqtt/rmqtt/blob/master/docs/en_US/bridge-egress-pulsar.md

[[bridges]]
# Whether to enable
enable = true
# Bridge name
name = "bridge_pulsar_1"
# The address of the Pulsar broker that the client will connect to using plain TCP.
# In this case, it's connecting to the local broker at port 6650.
servers = "pulsar://127.0.0.1:6650"
# The address of the Pulsar broker that the client would connect to using SSL/TLS.
# Uncomment this line to enable a secure connection to the local broker at port 6651.
#servers = "pulsar+ssl://127.0.0.1:6651"

# producer name prefix
producer_name_prefix = "producer_1"

# add a custom certificate chain from a file to authenticate the server in TLS connections
#cert_chain_file = "./rmqtt-bin/rmqtt.fullchain.pem"
#allow insecure TLS connection if set to true, defaults to false
#allow_insecure_connection = false
#whether hostname verification is enabled when insecure TLS connection is allowed, defaults to true
#tls_hostname_verification_enabled = true

#token(JWT, Biscuit)/ or oauth2
#auth.name = "token"
#auth.data = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyX2lkIiwiZXhwIjoxNjI2NzY5MjAwLCJpYXQiOjE2MjY3NjU2MDB9.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
#auth.name = "oauth2"
#auth.data = "{\"issuer_url\":\"https://example.com/oauth2/issuer\", \"credentials_url\":\"file:///path/to/credentials/file.json\"}"

[[bridges.entries]]
#Local topic filter: All messages matching this topic filter will be forwarded.
local.topic_filter = "local/topic1/egress/#"

remote.topic = "non-persistent://public/default/test1"
# forward all from data, including: from_type, from_node, from_ipaddress, from_clientid, from_username
#remote.forward_all_from = false
# forward all publish data, including: dup, retain, qos, packet_id, topic (required to forward), payload (required to forward)
#remote.forward_all_publish = false

#determines the target partition of the message. Messages with the same partition_key will be sent to the same partition.
#remote.partition_key = ""

#this affects the order of messages within a specific partition, not across partitions. If messages have the same ordering_key, they will be consumed in the order they were sent.
#Values: clientid, uuid, random or {type="random", len=10}
# clientid - use mqtt clientid
# uuid - uuid
# random - randomly generated
#remote.ordering_key = "clientid"
#remote.ordering_key = {type="random", len=10}

#Override namespace's replication
#remote.replicate_to = []

#current version of the schema
#remote.schema_version = ""

#user defined properties added to all messages
#remote.options.metadata = {}
#algorithm used to compress the messages, value: lz4,zlib,zstd,snappy
#remote.options.compression = "lz4"
#producer access mode: shared = 0, exclusive = 1, waitforexclusive = 2, exclusivewithoutfencing = 3
#remote.options.access_mode = 0

[[bridges.entries]]
#Local topic filter: All messages matching this topic filter will be forwarded.
local.topic_filter = "local/topic2/egress/#"

remote.topic = "non-persistent://public/default/test2"


