##--------------------------------------------------------------------
## rmqtt-topic-rewrite
##--------------------------------------------------------------------

# See more keys and their definitions at https://github.com/rmqtt/rmqtt/blob/master/docs/en_US/topic-rewrite.md

# action - Options are publish, subscribe, or all
# source_topic_filter - Topic filter for subscribing, unsubscribing, or publishing messages
# dest_topic - Destination topic
# regex - Regular expression

# Expressions can use ${clientid} to represent the client ID and ${username} to represent the client username.

rules = [
#    { action = "all", source_topic_filter = "x/+/#", dest_topic = "xx/$1/$2", regex = "^x/(.+)/(.+)$" },
#    { action = "all", source_topic_filter = "x/y/1", dest_topic = "xx/y/1" },
#    { action = "all", source_topic_filter = "x/y/#", dest_topic = "xx/y/$1", regex = "^x/y/(.+)$" },
#    { action = "all", source_topic_filter = "iot/cid/#", dest_topic = "iot/${clientid}/$1", regex = "^iot/cid/(.+)$" },
#    { action = "all", source_topic_filter = "iot/uname/#", dest_topic = "iot/${username}/$1", regex = "^iot/uname/(.+)$" },
#    { action = "all", source_topic_filter = "a/+/+/+", dest_topic = "aa/$1/$2/$3", regex = "^a/(.+)/(.+)/(.+)$" }
]

