##--------------------------------------------------------------------
## rmqtt-bridge-ingress-mqtt
##--------------------------------------------------------------------

# See more keys and their definitions at https://github.com/rmqtt/rmqtt/blob/master/docs/en_US/bridge-ingress-mqtt.md

[[bridges]]
# Whether to enable
enable = true
# Bridge name
name = "bridge_name_1"
# Client ID prefix
client_id_prefix = "prefix"
# Address and port of the remote MQTT broker
server = "127.0.0.1:2883"
# Username to connect to the remote MQTT broker
username = "rmqtt_u"
# Password to connect to the remote MQTT broker
password = "public"

# Maximum limit of clients connected to the remote MQTT broker
concurrent_client_limit = 5
# Connection timeout
connect_timeout = "20s"
# Keepalive interval
keepalive = "60s"
# Automatic reconnection interval
reconnect_interval = "5s"

## Whether to support retain message, true/false, default value: false
retain_available = false
## Whether to support storage messages, true/false, default value: false
storage_available = false
## Message expiration time, 0 means no expiration
expiry_interval = "5m"

# MQTT protocol version to use: v4, v5 corresponding to MQTT 3.1.1, 5.0
mqtt_ver = "v4"

## The following configuration is related to specific protocol versions
# Clean session
v4.clean_session = true

[[bridges.entries]]
# Choose 0, 1, 2, default: 0
remote.qos = 0
remote.topic = "$share/g/remote/topic1/ingress/#"

# Choose 0, 1, 2, or not set (follow message QoS)
local.qos = 1
local.topic = "local/topic1/ingress/${remote.topic}"
# true/false, default: false
local.retain = true

[[bridges.entries]]
# Choose 0, 1, 2
remote.qos = 1
remote.topic = "$share/g/remote/topic2/ingress"

# Choose 0, 1, 2, or not set (follow message QoS)
# local.qos = 0
local.topic = "local/topic2/ingress"
local.retain = false

[[bridges]]
# Whether to enable
enable = true
# Bridge name
name = "bridge_name_2"
# Client ID prefix
client_id_prefix = "prefix"
# Address and port of the remote MQTT broker
server = "127.0.0.1:2883"
# Username to connect to the remote MQTT broker
username = "rmqtt_u"
# Password to connect to the remote MQTT broker
password = "public"

# Maximum limit of clients connected to the remote MQTT broker
concurrent_client_limit = 5
# Connection timeout
connect_timeout = "20s"
# Keepalive interval
keepalive = "60s"
# Automatic reconnection interval
reconnect_interval = "5s"

## Whether to support retain message, true/false, default value: false
retain_available = false
## Whether to support storage messages, true/false, default value: false
storage_available = false
## Message expiration time, 0 means no expiration
expiry_interval = "5m"

# MQTT protocol version to use: v4, v5 corresponding to MQTT 3.1.1, 5.0
mqtt_ver = "v5"

## The following configuration is related to specific protocol versions
# Clean start
v5.clean_start = true
# Session expiry interval, 0 means the session ends immediately after the network disconnection
v5.session_expiry_interval = "0s"
# Limit the maximum number of QoS 1 and QoS 2 messages the client can process simultaneously
v5.receive_maximum = 16
# The maximum packet size negotiated between client and server
v5.maximum_packet_size = "1M"
# The maximum number of topic aliases negotiated between client and server
v5.topic_alias_maximum = 0

[[bridges.entries]]
# Choose 0, 1, 2, default: 0
remote.qos = 0
remote.topic = "$share/g/remote/topic3/ingress/#"

# Choose 0, 1, 2, or not set (follow message QoS)
local.qos = 1
local.topic = "local/topic3/ingress/${remote.topic}"
# true/false, default: false
local.retain = true

[[bridges.entries]]
# Choose 0, 1, 2
remote.qos = 1
remote.topic = "$share/g/remote/topic4/ingress"

# Choose 0, 1, 2, or not set (follow message QoS)
# local.qos = 0
local.topic = "local/topic4/ingress"
local.retain = false

