##--------------------------------------------------------------------
## rmqtt-cluster-broadcast
##--------------------------------------------------------------------

#grpc message type
message_type = 98
# The list of gRPC addresses for the nodes in the cluster.
# Each entry contains the node ID (e.g., 1, 2, 3) followed by the corresponding IP address and port.
# These addresses are used for inter-node communication within the cluster.
node_grpc_addrs = ["1@127.0.0.1:5363", "2@127.0.0.1:5364", "3@127.0.0.1:5365"]