[package]
name = "rmqtt-web-hook"
version = "0.1.2"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rmqtt.workspace = true
rmqtt-macros.workspace = true
serde = { workspace = true, features = ["derive"] }
backoff = { version = "0.4", features = ["futures", "tokio"] }