[package]
name = "rmqtt"
version = "0.2.4"
authors = ["rmqtt <rmqttd@126.com>"]
description = "MQTT Server for v3.1, v3.1.1 and v5.0 protocols"
repository = "https://github.com/rmqtt/rmqtt.git"
categories = ["network-programming"]
keywords = ["MQTT", "IoT", "messaging", "MQTT Server", "MQTT Broker"]
license = "MIT license, Apache-2.0 License"
exclude = [".gitignore", ".cargo/config"]
edition = "2021"

[lib]
name = "rmqtt"
path = "src/lib.rs"

[dependencies]
rmqtt-macros = "0.1"
ntex = { git = "https://github.com/rmqtt/ntex.git", branch = "0.3.16", features = ["rustls"] }
ntex-mqtt = { git = "https://github.com/rmqtt/ntex-mqtt", branch = "0.6.11" }
#ntex = { path = "../../ntex/ntex", features = ["rustls"]}
#ntex-mqtt = { path = "../../ntex-mqtt" }
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tonic = "0.6"
prost = "0.9"
once_cell = "1.10"
dashmap = "5.3"
ahash = "0.7"
bytes = { version = "1", features = ["serde"] }
bytestring = { version = "1", features = ["serde"] }
thiserror = "1.0"
anyhow = "1.0"
lazy_static = "1.4"
async-trait = "0.1"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
uuid = { version = "1.1", features = ["v4"] }
rand = "0.8"
crossbeam = "0.8"
governor = "0.3"
config = "0.11"
leaky-bucket = "0.12"
linked-hash-map = "0.5"
log = { version = "0.4", features = ["std"] }
slog = "2.7"
slog-async = "2.7"
slog-logfmt = "0.1"
base64 = "0.13"
bincode = "1.3"
url = { version = "2.2", default-features = false }
systemstat = "0.1"
itertools = "0.10"
reqwest = { version = "0.11", features = ["json"] }

[build-dependencies]
tonic-build = "0.6"
toml = "0.5"
chrono = "0.4"