[package]
name = "rmqtt"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
categories.workspace = true
keywords.workspace = true
exclude.workspace = true
rust-version.workspace = true

[lib]
name = "rmqtt"
path = "src/lib.rs"

[features]
default = []
debug = []

[dependencies]
rmqtt-macros = "0.1"
ntex = { git = "https://github.com/rmqtt/ntex.git", branch = "0.3.22", features = ["rustls"] }
ntex-mqtt = { git = "https://github.com/rmqtt/ntex-mqtt", branch = "0.6.23" }
#ntex = { path = "../../ntex/ntex", features = ["rustls"]}
#ntex-mqtt = { path = "../../ntex-mqtt" }
futures = "0.3"
tokio = { version = "1", features = ["sync", "time", "macros", "rt", "rt-multi-thread", "fs"] }
socket2 = { version = "0.5", features = ["all"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.9"
prost = "0.11"
once_cell = "1.18"
dashmap = "5.5"
ahash = "0.8"
bytes = { version = "1", features = ["serde"] }
bytestring = { version = "1", features = ["serde"] }
thiserror = "1.0"
anyhow = "1.0"
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
uuid = { version = "1.4", features = ["v4"] }
rand = "0.8"
crossbeam = "0.8"
governor = "0.6"
config = { version = "0.13", default-features = false, features = ["toml"] }
log = { version = "0.4", features = ["std"] }
slog = "2.7"
slog-term = "2.9"
slog-async = "2.8"
slog-stdlog = "4.1"
slog-scope = "4.4"
base64 = "0.21"
bincode = "1.3"
url = { version = "2.4", default-features = false }
systemstat = "0.2"
itertools = "0.12"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
rust-box = { version = "0.11", features = ["task-exec-queue", "task-exec-queue-rate", "std-ext", "dequemap", "stream-ext-leaky-bucket"] }
structopt = "0.3"
tokio-tungstenite = "0.21"
pin-project-lite = "0.2.13"
tokio-cron-scheduler = "0.9.4"
bitflags = "2.4"
leaky-bucket = "1.0"
scc = "2.0"
get_size = { package = "get-size", version = "0.1", features = ["derive"] }

[build-dependencies]
tonic-build = "0.9"
toml = "0.8"
chrono = { version = "0.4", default-features = false, features = ["clock"] }