[package]
name = "rmqtt"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
categories.workspace = true
keywords.workspace = true
exclude.workspace = true
rust-version.workspace = true

[lib]
name = "rmqtt"
path = "src/lib.rs"

[features]
default = []
debug = []

[dependencies]
rmqtt-macros = "0.1"
ntex = { git = "https://github.com/rmqtt/ntex.git", branch = "0.3.17", features = ["rustls"] }
ntex-mqtt = { git = "https://github.com/rmqtt/ntex-mqtt", branch = "0.6.14" }
#ntex = { path = "../../ntex/ntex", features = ["rustls"]}
#ntex-mqtt = { path = "../../ntex-mqtt" }
futures = "0.3"
tokio = { version = "1", features = ["sync", "time", "macros", "rt", "rt-multi-thread"] }
tonic = "0.8"
prost = "0.11"
once_cell = "1.10"
dashmap = "5.4"
ahash = "0.8"
bytes = { version = "1", features = ["serde"] }
bytestring = { version = "1", features = ["serde"] }
thiserror = "1.0"
anyhow = "1.0"
lazy_static = "1.4"
async-trait = "0.1"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
uuid = { version = "1.1", features = ["v4"] }
rand = "0.8"
crossbeam = "0.8"
governor = "0.3"
config = { version = "0.11.0", default-features = false, features = ["toml"] }
log = { version = "0.4", features = ["std"] }
slog = "2.7"
slog-term = "2.9"
slog-async = "2.7"
slog-stdlog = "4.1"
slog-scope = "4.4"
base64 = "0.13"
bincode = "1.3"
url = { version = "2.2", default-features = false }
systemstat = "0.1"
itertools = "0.10"
reqwest = { version = "0.11", features = ["json"] }
rust-box = { version = "0.6.1", features = ["task-exec-queue", "task-exec-queue-rate", "std-ext", "dequemap"] }
structopt = "0.3"
tokio-tungstenite = "0.18"
pin-project-lite = "0.2.5"

[build-dependencies]
tonic-build = "0.8"
toml = "0.5"
chrono = { version = "0.4", default-features = false, features = [] }