[package]
name = "rmqtt-retainer"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmqtt.workspace = true
rmqtt-macros.workspace = true
rmqtt-storage = { version = "0.5", default-features = false, features = ["ttl", "len"]}
#rmqtt-storage = { path = "../../../rmqtt-storage", default-features = false, features = ["ttl", "len"]}
serde = { workspace = true, features = ["derive"] }
futures-time = "3.0.0"